const env = import.meta.env

export default {
  VITE_CLIENT_BASE_URL: env.VITE_CLIENT_BASE_URL,
  VITE_API_BASE_URL: env.VITE_API_BASE_URL,
  VITE_SERVER_BASE_URL: env.VITE_SERVER_BASE_URL,
  VITE_CLIENT_ID: env.VITE_CLIENT_ID,
}